# Generated by Django 5.0.6 on 2024-05-22 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=233, unique=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
                ('institute', models.CharField(max_length=233)),
                ('grade', models.CharField(blank=True, default='A', max_length=1)),
                ('division', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='First', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('hands_on', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=100)),
                ('address', models.CharField(blank=True, max_length=233)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.education')),
                ('skill', models.ManyToManyField(to='app.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
