# Generated by Django 5.0.6 on 2024-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.ManyToManyField(to='app.education'),
        ),
    ]
